### ISSUE TITLE
Is it possible to add support for Firefox Developer Edition please?

### ISSUE THREAD

**Issue by nikitavoloboev** [nikipore/alfred-firefoxbookmarks#6]
I would really love if I could search bookmarks from [this application](https://www.mozilla.org/en-US/firefox/developer/). Currently this workflow does not let me do that. 😞

**Comment by a-x-** [comment]
Firefox nightly too...

**Comment by nikipore** [comment]
Fixed with https://github.com/nikipore/alfred-firefoxbookmarks/pull/8. Thanks @jackblackevo!

**Comment by a-x-** [comment]
> no such column: moz_places.favicon_id

```
Starting debug for 'Firefox Bookmarks'

[2017-11-02 15:13:42][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "bookmarks.py", line 71, in <module>
    alfred.write(alfred.xml(results(db, query), maxresults=_MAX_RESULTS))
  File "/Users/mxtnr/preferences/alfred/Alfred.alfredpreferences/workflows/user.workflow.44266729-E92C-4956-80E4-E9EC6282DDAC/alfred.py", line 87, in xml
    for item in itertools.islice(items, maxresults):
  File "bookmarks.py", line 38, in results
    for result in db.execute(sql(query)):
sqlite3.OperationalError: no such column: moz_places.favicon_id
```

**Comment by a-x-** [comment]
FirefoxNightly 58.0a1 (2017-11-02)

> no such column: moz_places.favicon_id

```
[2017-11-02 15:13:42][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "bookmarks.py", line 71, in <module>
    alfred.write(alfred.xml(results(db, query), maxresults=_MAX_RESULTS))
  File "/Users/mxtnr/preferences/alfred/Alfred.alfredpreferences/workflows/user.workflow.44266729-E92C-4956-80E4-E9EC6282DDAC/alfred.py", line 87, in xml
    for item in itertools.islice(items, maxresults):
  File "bookmarks.py", line 38, in results
    for result in db.execute(sql(query)):
sqlite3.OperationalError: no such column: moz_places.favicon_id
```

**Comment by nikipore** [comment]
Did you update your plugin? In the HEAD revision there is no reference to a field `mozplaces.favicon_id`.

**Comment by a-x-** [comment]
hm,
I downloaded obsolete https://github.com/nikipore/alfred-firefoxbookmarks/blob/master/Firefox%20Bookmarks.alfredworkflow

Can you rebuild it?

I'm gonna replace files locally now

**Comment by nikipore** [comment]
Done.
